{% extends "base.html" %}

{% block content %}
<div class="container py-5">
    <div class="error-container">
        <div class="row">
            <div class="col-lg-6 d-flex align-items-center justify-content-center">
                <div class="error-image-container">
                    <div class="error-code">
                        <span>5</span>
                        <span>0</span>
                        <span>0</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-start">
                <h1 class="error-title mb-4">Server Error</h1>
                <p class="error-message mb-4">Oops! Something went wrong on our end.</p>
                <p class="error-description mb-5">Our team has been notified and is working to fix the issue. Please try again later or contact support if the problem persists.</p>
                <div class="error-actions">
                    <a href="{{ url_for('main.index') }}" class="btn btn-primary btn-lg">
                        <i class="fas fa-home me-2"></i>Go Home
                    </a>
                    <a href="javascript:history.back()" class="btn btn-outline-primary btn-lg ms-3">
                        <i class="fas fa-arrow-left me-2"></i>Go Back
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
